@startuml
:客户端点击办卡;
if(读取身份证) then(读取到身份信息)
    :返回身份证信息;
    :用户输入手机号码;
    if(调用his用户建档接口) then(建档成功)
        :用户选择充值类型;
        :用户输入充值金额;
        if(调用银行交易接口) then(调用银行交易接口成功)
            :返回交易信息;
            :用户扫描二维码;
            if(调用银行交易结果查询接口) then(成功)
                if(调用his充值接口) then(his充值成功)
                    if(调用打印机) then(打印成功)
                        if(调用发卡器写卡) then(写卡成功)
                            :调用发卡器退卡;
                        else(写卡失败)
                            :回收卡;
                        endif
                        :返回消息;
                            end
                    else(打印失败)
                        :返回消息;
                    endif
                        end
                else(his充值失败)
                    :返回消息;
                endif
                    end
            else(失败)
                :调用银行退费接口(暂时返回消息);
            endif
                end
        else(调用银行交易接口失败)
            :撤销用户建档;
        endif
        end
    else(建档失败)
        :返回消息;
    endif
        end
else(读取身份失败)
    :返回消息;
endif
    end
@enduml