@startuml
:充值;
if(允许进卡) then(成功)
    if (是否有卡?) then (有卡)
        if (移动到射频卡位?) then (移动成功)
            if(读卡) then(读卡成功)

            if(调用his患者信息接口/卡信息接口) then (查询患者信息成功)
                :用户选择充值类型;
                :用户输入充值金额;
                if (调用银行交易接口) then (成功)
                :返回交易信息(二维码);
                else(失败)
                :返回消息;
                endif
                end
            else(查询患者信息失败)
                :返回消息;
            endif
                end

            else(读卡失败)
                :返回消息;
            endif
                end
        else (移动失败)
        :返回消息;
        stop
        endif
    else (无卡)
    :返回消息;
        stop
    endif
else(允许进卡失败)
:返回消息;
endif
end
@enduml